import type { Airport } from './airport.types'

export const AIRPORTS = [
  { code: 'ICN', nameKo: '인천국제공항', nameEn: 'Incheon International Airport', cityKo: '서울', timezone: 'Asia/Seoul' },
  { code: 'GMP', nameKo: '김포국제공항', nameEn: 'Gimpo International Airport', cityKo: '서울', timezone: 'Asia/Seoul' },
  { code: 'PUS', nameKo: '김해국제공항', nameEn: 'Gimhae International Airport', cityKo: '부산', timezone: 'Asia/Seoul', aliases: ['부산'] },
  { code: 'CJU', nameKo: '제주국제공항', nameEn: 'Jeju International Airport', cityKo: '제주', timezone: 'Asia/Seoul' },
  { code: 'TAE', nameKo: '대구국제공항', nameEn: 'Daegu International Airport', cityKo: '대구', timezone: 'Asia/Seoul' },
  { code: 'KIX', nameKo: '간사이국제공항', nameEn: 'Kansai International Airport', cityKo: '오사카', timezone: 'Asia/Tokyo', aliases: ['교토', '고베'] },
  { code: 'NRT', nameKo: '나리타국제공항', nameEn: 'Narita International Airport', cityKo: '도쿄', timezone: 'Asia/Tokyo' },
  { code: 'HND', nameKo: '하네다공항', nameEn: 'Haneda Airport', cityKo: '도쿄', timezone: 'Asia/Tokyo' },
  { code: 'FUK', nameKo: '후쿠오카공항', nameEn: 'Fukuoka Airport', cityKo: '후쿠오카', timezone: 'Asia/Tokyo' },
  { code: 'CTS', nameKo: '신치토세공항', nameEn: 'New Chitose Airport', cityKo: '삿포로', timezone: 'Asia/Tokyo' },
  { code: 'OKA', nameKo: '나하공항', nameEn: 'Naha Airport', cityKo: '오키나와', timezone: 'Asia/Tokyo' },
  { code: 'TPE', nameKo: '타오위안국제공항', nameEn: 'Taoyuan International Airport', cityKo: '타이베이', timezone: 'Asia/Taipei' },
  { code: 'HKG', nameKo: '홍콩국제공항', nameEn: 'Hong Kong International Airport', cityKo: '홍콩', timezone: 'Asia/Hong_Kong' },
  { code: 'BKK', nameKo: '수완나품국제공항', nameEn: 'Suvarnabhumi Airport', cityKo: '방콕', timezone: 'Asia/Bangkok' },
  { code: 'DAD', nameKo: '다낭국제공항', nameEn: 'Da Nang International Airport', cityKo: '다낭', timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'SIN', nameKo: '창이국제공항', nameEn: 'Singapore Changi Airport', cityKo: '싱가포르', timezone: 'Asia/Singapore' },
  { code: 'PVG', nameKo: '푸둥국제공항', nameEn: 'Shanghai Pudong International Airport', cityKo: '상하이', timezone: 'Asia/Shanghai' },
  { code: 'PEK', nameKo: '베이징서우두국제공항', nameEn: 'Beijing Capital International Airport', cityKo: '베이징', timezone: 'Asia/Shanghai' },
  { code: 'LAX', nameKo: '로스앤젤레스국제공항', nameEn: 'Los Angeles International Airport', cityKo: '로스앤젤레스', timezone: 'America/Los_Angeles' },
  { code: 'JFK', nameKo: '존에프케네디국제공항', nameEn: 'John F. Kennedy International Airport', cityKo: '뉴욕', timezone: 'America/New_York' },
  { code: 'CDG', nameKo: '샤를드골국제공항', nameEn: 'Charles de Gaulle Airport', cityKo: '파리', timezone: 'Europe/Paris' },
  { code: 'LHR', nameKo: '히스로공항', nameEn: 'Heathrow Airport', cityKo: '런던', timezone: 'Europe/London' },
  { code: 'FRA', nameKo: '프랑크푸르트공항', nameEn: 'Frankfurt Airport', cityKo: '프랑크푸르트', timezone: 'Europe/Berlin' },
  { code: 'SYD', nameKo: '시드니국제공항', nameEn: 'Sydney Airport', cityKo: '시드니', timezone: 'Australia/Sydney' },
  { code: 'GUM', nameKo: '괌국제공항', nameEn: 'Antonio B. Won Pat International Airport', cityKo: '괌', timezone: 'Pacific/Guam' },
  { code: 'KWJ', nameKo: '광주공항', nameEn: 'Gwangju Airport', cityKo: '광주', timezone: 'Asia/Seoul' },
  { code: 'USN', nameKo: '울산공항', nameEn: 'Ulsan Airport', cityKo: '울산', timezone: 'Asia/Seoul' },
  { code: 'KPO', nameKo: '포항경주공항', nameEn: 'Pohang Gyeongju Airport', cityKo: '포항', timezone: 'Asia/Seoul', aliases: ['경주'] },
  { code: 'RSU', nameKo: '여수공항', nameEn: 'Yeosu Airport', cityKo: '여수', timezone: 'Asia/Seoul' },
  { code: 'YNY', nameKo: '양양국제공항', nameEn: 'Yangyang International Airport', cityKo: '양양', timezone: 'Asia/Seoul', aliases: ['속초', '강릉'] },
  { code: 'NGO', nameKo: '주부국제공항', nameEn: 'Chubu Centrair International Airport', cityKo: '나고야', timezone: 'Asia/Tokyo', aliases: ['센트레아'] },
  { code: 'ITM', nameKo: '오사카국제공항', nameEn: 'Osaka International Airport', cityKo: '오사카', timezone: 'Asia/Tokyo', aliases: ['이타미'] },
  { code: 'UKB', nameKo: '고베공항', nameEn: 'Kobe Airport', cityKo: '고베', timezone: 'Asia/Tokyo' },
  { code: 'MMY', nameKo: '미야코공항', nameEn: 'Miyako Airport', cityKo: '미야코지마시', timezone: 'Asia/Tokyo' },
  { code: 'MYJ', nameKo: '마쓰야마공항', nameEn: 'Matsuyama Airport', cityKo: '마쓰야마', timezone: 'Asia/Tokyo' },
  { code: 'MFM', nameKo: '마카오국제공항', nameEn: 'Macau International Airport', cityKo: '마카오', timezone: 'Asia/Macau' },
  { code: 'SGN', nameKo: '떤선녓국제공항', nameEn: 'Tan Son Nhat International Airport', cityKo: '호치민', timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'HAN', nameKo: '노이바이국제공항', nameEn: 'Noi Bai International Airport', cityKo: '하노이', timezone: 'Asia/Ho_Chi_Minh', aliases: ['사파'] },
  { code: 'CXR', nameKo: '깜라인국제공항', nameEn: 'Cam Ranh International Airport', cityKo: '나트랑', timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'PQC', nameKo: '푸꾸옥국제공항', nameEn: 'Phu Quoc International Airport', cityKo: '푸꾸옥', timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'HKT', nameKo: '푸켓국제공항', nameEn: 'Phuket International Airport', cityKo: '푸켓', timezone: 'Asia/Bangkok' },
  { code: 'CEB', nameKo: '막탄세부국제공항', nameEn: 'Mactan-Cebu International Airport', cityKo: '세부', timezone: 'Asia/Manila' },
  { code: 'MPH', nameKo: '고돈반타얀공항', nameEn: 'Godofredo P. Ramos Airport', cityKo: '보라카이', timezone: 'Asia/Manila', aliases: ['칼리보', '카티클란'] },
  { code: 'MNL', nameKo: '니노이아키노국제공항', nameEn: 'Ninoy Aquino International Airport', cityKo: '마닐라', timezone: 'Asia/Manila' },
  { code: 'BKI', nameKo: '코타키나발루국제공항', nameEn: 'Kota Kinabalu International Airport', cityKo: '코타키나발루', timezone: 'Asia/Kuching' },
  { code: 'KUL', nameKo: '쿠알라룸푸르국제공항', nameEn: 'Kuala Lumpur International Airport', cityKo: '쿠알라룸푸르', timezone: 'Asia/Kuala_Lumpur' },
  { code: 'DPS', nameKo: '응우라라이국제공항', nameEn: 'Ngurah Rai International Airport', cityKo: '발리', timezone: 'Asia/Makassar', aliases: ['덴파사르'] },
  { code: 'CGK', nameKo: '수카르노하타국제공항', nameEn: 'Soekarno-Hatta International Airport', cityKo: '자카르타', timezone: 'Asia/Jakarta' },
  { code: 'FCO', nameKo: '피우미치노공항', nameEn: 'Leonardo da Vinci International Airport', cityKo: '로마', timezone: 'Europe/Rome', aliases: ['레오나르도다빈치'] },
  { code: 'MXP', nameKo: '말펜사공항', nameEn: 'Milan Malpensa Airport', cityKo: '밀라노', timezone: 'Europe/Rome' },
  { code: 'VCE', nameKo: '마르코폴로공항', nameEn: 'Venice Marco Polo Airport', cityKo: '베네치아', timezone: 'Europe/Rome' },
  { code: 'FLR', nameKo: '피렌체공항', nameEn: 'Florence Airport', cityKo: '피렌체', timezone: 'Europe/Rome' },
  { code: 'NAP', nameKo: '나폴리국제공항', nameEn: 'Naples International Airport', cityKo: '나폴리', timezone: 'Europe/Rome' },
  { code: 'BCN', nameKo: '엘프라트공항', nameEn: 'Josep Tarradellas Barcelona-El Prat Airport', cityKo: '바르셀로나', timezone: 'Europe/Madrid' },
  { code: 'LIS', nameKo: '움베르투델가두공항', nameEn: 'Humberto Delgado Airport', cityKo: '리스본', timezone: 'Europe/Lisbon' },
  { code: 'OPO', nameKo: '포르투공항', nameEn: 'Francisco Sá Carneiro Airport', cityKo: '포르투', timezone: 'Europe/Lisbon' },
  { code: 'NCE', nameKo: '니스코트다쥐르공항', nameEn: "Nice Côte d'Azur Airport", cityKo: '니스', timezone: 'Europe/Paris' },
  { code: 'PRG', nameKo: '바츨라프하벨공항', nameEn: 'Václav Havel Airport Prague', cityKo: '프라하', timezone: 'Europe/Prague' },
  { code: 'AMS', nameKo: '스히폴공항', nameEn: 'Amsterdam Airport Schiphol', cityKo: '암스테르담', timezone: 'Europe/Amsterdam' },
  { code: 'ZRH', nameKo: '취리히공항', nameEn: 'Zurich Airport', cityKo: '취리히', timezone: 'Europe/Zurich', aliases: ['인터라켄', '베른'] },
  { code: 'GVA', nameKo: '제네바공항', nameEn: 'Geneva Airport', cityKo: '제네바', timezone: 'Europe/Zurich' },
  { code: 'VIE', nameKo: '비엔나국제공항', nameEn: 'Vienna International Airport', cityKo: '비엔나', timezone: 'Europe/Vienna', aliases: ['빈'] },
  { code: 'SZG', nameKo: '잘츠부르크공항', nameEn: 'Salzburg Airport', cityKo: '잘츠부르크', timezone: 'Europe/Vienna', aliases: ['할슈타트'] },
  { code: 'BUD', nameKo: '부다페스트공항', nameEn: 'Budapest Ferenc Liszt International Airport', cityKo: '부다페스트', timezone: 'Europe/Budapest' },
  { code: 'HEL', nameKo: '헬싱키반타공항', nameEn: 'Helsinki-Vantaa Airport', cityKo: '헬싱키', timezone: 'Europe/Helsinki' },
  { code: 'IST', nameKo: '이스탄불공항', nameEn: 'Istanbul Airport', cityKo: '이스탄불', timezone: 'Europe/Istanbul' },
  { code: 'DXB', nameKo: '두바이국제공항', nameEn: 'Dubai International Airport', cityKo: '두바이', timezone: 'Asia/Dubai' },
  { code: 'DOH', nameKo: '하마드국제공항', nameEn: 'Hamad International Airport', cityKo: '도하', timezone: 'Asia/Qatar' },
  { code: 'SFO', nameKo: '샌프란시스코국제공항', nameEn: 'San Francisco International Airport', cityKo: '샌프란시스코', timezone: 'America/Los_Angeles' },
  { code: 'LAS', nameKo: '해리리드국제공항', nameEn: 'Harry Reid International Airport', cityKo: '라스베이거스', timezone: 'America/Los_Angeles' },
  { code: 'HNL', nameKo: '호놀룰루국제공항', nameEn: 'Daniel K. Inouye International Airport', cityKo: '호놀룰루', timezone: 'Pacific/Honolulu' },
  { code: 'YVR', nameKo: '밴쿠버국제공항', nameEn: 'Vancouver International Airport', cityKo: '벤쿠버', timezone: 'America/Vancouver' },
  { code: 'YYZ', nameKo: '토론토피어슨국제공항', nameEn: 'Toronto Pearson International Airport', cityKo: '토론토', timezone: 'America/Toronto' },
  { code: 'CUN', nameKo: '칸쿤국제공항', nameEn: 'Cancún International Airport', cityKo: '칸쿤', timezone: 'America/Cancun' },
] as const satisfies readonly Airport[]

export type AirportCode = (typeof AIRPORTS)[number]['code']
