export const DESTINATION_TO_COUNTRY = {
  서울: 'South Korea',
  부산: 'South Korea',
  제주: 'South Korea',
  강릉: 'South Korea',
  경주: 'South Korea',
  여수: 'South Korea',
  전주: 'South Korea',
  속초: 'South Korea',
  삼척: 'South Korea',
  인천: 'South Korea',
  대구: 'South Korea',
  대전: 'South Korea',
  광주: 'South Korea',
  단양: 'South Korea',
  평창: 'South Korea',
  포천: 'South Korea',
  진안: 'South Korea',
  도쿄: 'Japan',
  오사카: 'Japan',
  교토: 'Japan',
  후쿠오카: 'Japan',
  삿포로: 'Japan',
  오키나와: 'Japan',
  방콕: 'Thailand',
  푸켓: 'Thailand',
  싱가포르: 'Singapore',
  '베트남 다낭': 'Vietnam',
  '베트남 호치민': 'Vietnam',
  '베트남 하노이': 'Vietnam',
  발리: 'Indonesia',
  세부: 'Philippines',
  코타키나발루: 'Malaysia',
  홍콩: 'China',
  마카오: 'China',
  타이베이: 'Taiwan',
  상하이: 'China',
  파리: 'France',
  런던: 'United Kingdom',
  로마: 'Italy',
  바르셀로나: 'Spain',
  프라하: 'Czech Republic',
  암스테르담: 'Netherlands',
  '스위스 취리히': 'Switzerland',
  뉴욕: 'United States of America',
  로스앤젤레스: 'United States of America',
  '하와이 호놀룰루': 'United States of America',
  샌프란시스코: 'United States of America',
  라스베이거스: 'United States of America',
  칸쿤: 'Mexico',
} as const

export const DESTINATION_TO_REGION = {
  서울: '서울',
  부산: '부산',
  제주: '제주',
  강릉: '강원도',
  경주: '경상북도',
  여수: '전라남도',
  전주: '전라북도',
  속초: '강원도',
  삼척: '강원도',
  인천: '인천',
  대구: '대구',
  대전: '대전',
  광주: '광주',
  단양: '충청북도',
  평창: '강원도',
  포천: '경기도',
  진안: '전라북도',
  도쿄: '간토',
  오사카: '간사이',
  교토: '간사이',
  후쿠오카: '규슈',
  삿포로: '홋카이도',
  오키나와: '오키나와',
  방콕: '태국',
  싱가포르: '싱가포르',
  '베트남 다낭': '베트남',
  '베트남 호치민': '베트남',
  '베트남 하노이': '베트남',
  발리: '인도네시아',
  세부: '필리핀',
  푸켓: '태국',
  코타키나발루: '말레이시아',
  홍콩: '홍콩',
  마카오: '마카오',
  타이베이: '대만',
  상하이: '중국',
  파리: '프랑스',
  런던: '영국',
  로마: '이탈리아',
  바르셀로나: '스페인',
  프라하: '체코',
  암스테르담: '네덜란드',
  '스위스 취리히': '스위스',
  뉴욕: '미국',
  로스앤젤레스: '미국',
  '하와이 호놀룰루': '미국',
  샌프란시스코: '미국',
  라스베이거스: '미국',
  칸쿤: '멕시코',
} as const satisfies Record<keyof typeof DESTINATION_TO_COUNTRY, string>

export const COUNTRY_TO_ISO3 = {
  'South Korea': 'KOR',
  Japan: 'JPN',
  Thailand: 'THA',
  Singapore: 'SGP',
  Vietnam: 'VNM',
  Indonesia: 'IDN',
  Philippines: 'PHL',
  Malaysia: 'MYS',
  China: 'CHN',
  Taiwan: 'TWN',
  France: 'FRA',
  'United Kingdom': 'GBR',
  Italy: 'ITA',
  Spain: 'ESP',
  'Czech Republic': 'CZE',
  Netherlands: 'NLD',
  Switzerland: 'CHE',
  'United States of America': 'USA',
  Mexico: 'MEX',
} as const satisfies Record<(typeof DESTINATION_TO_COUNTRY)[keyof typeof DESTINATION_TO_COUNTRY], string>

export type DestinationName = keyof typeof DESTINATION_TO_COUNTRY
export type CountryName = (typeof DESTINATION_TO_COUNTRY)[DestinationName]
export type TripRegionName = (typeof DESTINATION_TO_REGION)[DestinationName]

export function isDestinationName(value: string): value is DestinationName {
  return value in DESTINATION_TO_COUNTRY
}

export function getCountryByDestination(destination: string): CountryName | undefined {
  if (!isDestinationName(destination)) return undefined
  return DESTINATION_TO_COUNTRY[destination]
}

export function getRegionByDestination(destination: string): string {
  if (!isDestinationName(destination)) return destination
  return DESTINATION_TO_REGION[destination]
}
