import type { Airline } from './airline.types'

export const AIRLINES = [
  { code: 'KE', nameKo: '대한항공', nameEn: 'Korean Air' },
  { code: 'OZ', nameKo: '아시아나항공', nameEn: 'Asiana Airlines' },
  { code: '7C', nameKo: '제주항공', nameEn: 'Jeju Air' },
  { code: 'LJ', nameKo: '진에어', nameEn: 'Jin Air' },
  { code: 'TW', nameKo: '티웨이항공', nameEn: "T'way Air" },
  { code: 'BX', nameKo: '에어부산', nameEn: 'Air Busan' },
  { code: 'RS', nameKo: '에어서울', nameEn: 'Air Seoul' },
  { code: 'ZE', nameKo: '이스타항공', nameEn: 'Eastar Jet' },
  { code: 'RF', nameKo: '에어로케이', nameEn: 'Aero K' },
  { code: 'YP', nameKo: '에어프레미아', nameEn: 'Air Premia' },
  { code: 'NH', nameKo: '전일본공수', nameEn: 'All Nippon Airways' },
  { code: 'JL', nameKo: '일본항공', nameEn: 'Japan Airlines' },
  { code: 'CI', nameKo: '중화항공', nameEn: 'China Airlines' },
  { code: 'BR', nameKo: '에바항공', nameEn: 'EVA Air' },
  { code: 'CX', nameKo: '캐세이퍼시픽', nameEn: 'Cathay Pacific' },
  { code: 'SQ', nameKo: '싱가포르항공', nameEn: 'Singapore Airlines' },
  { code: 'TG', nameKo: '타이항공', nameEn: 'Thai Airways' },
  { code: 'VJ', nameKo: '비엣젯항공', nameEn: 'VietJet Air' },
  { code: 'VN', nameKo: '베트남항공', nameEn: 'Vietnam Airlines' },
  { code: 'MU', nameKo: '중국동방항공', nameEn: 'China Eastern Airlines' },
  { code: 'CZ', nameKo: '중국남방항공', nameEn: 'China Southern Airlines' },
  { code: 'CA', nameKo: '중국국제항공', nameEn: 'Air China' },
  { code: 'UA', nameKo: '유나이티드항공', nameEn: 'United Airlines' },
  { code: 'DL', nameKo: '델타항공', nameEn: 'Delta Air Lines' },
  { code: 'AA', nameKo: '아메리칸항공', nameEn: 'American Airlines' },
  { code: 'AF', nameKo: '에어프랑스', nameEn: 'Air France' },
  { code: 'LH', nameKo: '루프트한자', nameEn: 'Lufthansa' },
  { code: 'BA', nameKo: '영국항공', nameEn: 'British Airways' },
  { code: 'QF', nameKo: '콴타스항공', nameEn: 'Qantas' },
  { code: 'EK', nameKo: '에미레이트항공', nameEn: 'Emirates' },
  { code: 'MM', nameKo: '피치항공', nameEn: 'Peach Aviation' },
  { code: 'GK', nameKo: '젯스타재팬', nameEn: 'Jetstar Japan' },
  { code: 'IT', nameKo: '타이거에어대만', nameEn: 'Tigerair Taiwan' },
  { code: 'JX', nameKo: '스타룩스항공', nameEn: 'Starlux Airlines' },
  { code: 'AK', nameKo: '에어아시아', nameEn: 'AirAsia' },
  { code: 'D7', nameKo: '에어아시아엑스', nameEn: 'AirAsia X' },
  { code: 'FD', nameKo: '타이에어아시아', nameEn: 'Thai AirAsia' },
  { code: 'SL', nameKo: '타이라이언에어', nameEn: 'Thai Lion Air' },
  { code: 'PR', nameKo: '필리핀항공', nameEn: 'Philippine Airlines' },
  { code: '5J', nameKo: '세부퍼시픽', nameEn: 'Cebu Pacific' },
  { code: 'GA', nameKo: '가루다인도네시아', nameEn: 'Garuda Indonesia' },
  { code: 'QR', nameKo: '카타르항공', nameEn: 'Qatar Airways' },
  { code: 'TK', nameKo: '터키항공', nameEn: 'Turkish Airlines' },
  { code: 'AY', nameKo: '핀에어', nameEn: 'Finnair' },
  { code: 'KL', nameKo: 'KLM네덜란드항공', nameEn: 'KLM Royal Dutch Airlines' },
  { code: 'AC', nameKo: '에어캐나다', nameEn: 'Air Canada' },
  { code: 'HA', nameKo: '하와이안항공', nameEn: 'Hawaiian Airlines' },
  { code: 'VS', nameKo: '버진애틀랜틱', nameEn: 'Virgin Atlantic' },
  { code: 'AZ', nameKo: 'ITA항공', nameEn: 'ITA Airways' },
] as const satisfies readonly Airline[]

export type AirlineCode = (typeof AIRLINES)[number]['code']
